keys:
  # Your personal key (for encrypting/decrypting locally)
  - &admin age126y7n5guy5ezvegpu6luttnu6qp0utu4acmzcuruzxww4ku0e54srul0xa
  - &eridanus age16u7ml3ne6rd4a3uvq2wh7a7q542vnx7zemy200eus8sl0w4nt95qrf2g5t
  - &vela age15zxlzqt5tjs3vnujkwytmdz7z7hynrt95paj8fe9myzq0fnh7udqcy2dmz
  - &andromeda age1l2dwsyhapv4la4wx0f7j5pctsq54wsdlmfep534mqvnl84wqfpyqd7fw2p
  - &caelum age1wyvwgs0z0t84wl6teje9h6ejf7j8862yv3g3t9k2ulcy6wwpv9wqqnmz60
  - &orion age1mfrxpenlf07wk9swxqdanedz9leq7x3kagadwlualj8584ns7axsn6ynzg
  - &lyra age1xsxufzc7sj8zpatk7xqaung63p3lwj00nn364l47fmfd0fnpv5sqcmyvmj
  - &horologium age1zf4645x6mjuv0v7rcm33t8tspjv4gtpa9nwzdxf6czsjrwpy7c6s9q095g

creation_rules:
  # Default: encrypt for admin (you)
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *admin
          - *eridanus
          - *vela
          - *andromeda
          - *caelum
          - *orion
          - *lyra
          - *horologium
