{ config, pkgs, ... }:
{
  # ── Unbound Recursive DNS ─────────────────────────────────────────────────
  # Listens on all VLAN interfaces except Guest (VLAN 20)
  # Provides: recursive resolution, local hostnames (.lan), ad-blocking

  services.unbound = {
    enable = true;
    settings = {

      server = {
        # Listen on all VLAN gateway IPs (not Guest)
        interface = [
          "10.40.10.1"   # LAN
          "10.40.30.1"   # Management
          "10.40.40.1"   # Servers
          "10.40.50.1"   # IoT
          "10.40.60.1"   # Tor
          "127.0.0.1"    # localhost
        ];

        port = 53;
        do-ip4 = true;
        do-ip6 = false;
        do-udp = true;
        do-tcp = true;

        # Allow queries from trusted VLANs only
        access-control = [
          "0.0.0.0/0 refuse"
          "127.0.0.0/8 allow"
          "10.40.10.0/24 allow"   # LAN
          "10.40.30.0/24 allow"   # Management
          "10.40.40.0/24 allow"   # Servers
          "10.40.50.0/24 allow"   # IoT
          "10.40.60.0/24 allow"   # Tor
        ];

        # Performance & security
        num-threads = 2;
        cache-min-ttl = 300;
        cache-max-ttl = 86400;
        hide-identity = true;
        hide-version = true;
        harden-glue = true;
        harden-dnssec-stripped = true;
        use-caps-for-id = true;
        prefetch = true;
        prefetch-key = true;

        # DNSSEC validation
        auto-trust-anchor-file = "/var/lib/unbound/root.key";

        # Ad-blocking blocklist (generated by systemd timer below)
        include = [ "/var/lib/unbound/blocklist.conf" ];

        # ── Local hostnames (.lan) ──────────────────────────────────────────
        # Servers (VLAN 40)
        local-zone = [ "\"lan.\" static" ];

        local-data = [
          "\"orion.lan.        IN A 10.40.10.1\""
          "\"caelum.lan.       IN A 10.40.40.101\""
          "\"andromeda.lan.    IN A 10.40.40.104\""
          "\"eridanus.lan.     IN A 10.40.40.105\""
          "\"ha.lan.           IN A 10.40.40.115\""
          # Management (VLAN 30)
          "\"unifi-ap.lan.     IN A 10.40.30.120\""
          # IoT (VLAN 50)
          "\"everything-presence.lan. IN A 10.40.50.100\""
          "\"bed-presence.lan.        IN A 10.40.50.101\""
          "\"aqara-hub.lan.           IN A 10.40.50.103\""
        ];

        # Reverse DNS for .lan hosts
        local-data-ptr = [
          "\"10.40.10.1      orion.lan\""
          "\"10.40.40.101    caelum.lan\""
          "\"10.40.40.104    andromeda.lan\""
          "\"10.40.40.105    eridanus.lan\""
          "\"10.40.40.115    ha.lan\""
          "\"10.40.30.120    unifi-ap.lan\""
          "\"10.40.50.100    everything-presence.lan\""
          "\"10.40.50.101    bed-presence.lan\""
          "\"10.40.50.103    aqara-hub.lan\""
        ];
      };

      # Unbound will resolve directly from root servers
      forward-zone = [
        {
          name = ".";
          forward-tls-upstream = true;
          forward-addr = [
            "9.9.9.9@853#dns.quad9.net"
            "149.112.112.112@853#dns.quad9.net"
          ];
        }
      ];
    };
  };

  # Open port 53 on trusted VLAN interfaces
  # (replaces the existing per-interface allowedTCPPorts/allowedUDPPorts for port 53)
  networking.firewall.interfaces = {
    vlan10 = { allowedTCPPorts = [ 53 9090 ]; allowedUDPPorts = [ 53 67 ]; };
    vlan30 = { allowedTCPPorts = [ 53 9090 ]; allowedUDPPorts = [ 53 67 ]; };
    vlan40 = { allowedTCPPorts = [ 53 ];      allowedUDPPorts = [ 53 67 ]; };
    vlan50 = { allowedTCPPorts = [ 53 ];      allowedUDPPorts = [ 53 67 ]; };
    vlan20 = { allowedUDPPorts = [ 67 ]; };  # No port 53 — Guest uses 1.1.1.1 directly
  };

  # ── Ad-blocking blocklist ──────────────────────────────────────────────────
  # Downloads StevenBlack unified hosts list and converts to Unbound format
  # Runs on boot and weekly via systemd timer

  systemd.services.unbound-blocklist = {
    description = "Update Unbound ad-blocking blocklist";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    serviceConfig = {
      Type = "oneshot";
      ExecStart = pkgs.writeScript "update-blocklist" ''
        #!${pkgs.bash}/bin/bash
        set -e
        TMPFILE=$(mktemp)
        OUTFILE=/var/lib/unbound/blocklist.conf

        echo "Downloading blocklist..."
        ${pkgs.curl}/bin/curl -sSf \
          "https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts" \
          -o "$TMPFILE"

        echo "Converting to Unbound format..."
        grep "^0\.0\.0\.0" "$TMPFILE" \
          | awk '{print $2}' \
          | grep -v "^0\.0\.0\.0$" \
          | grep -v "^#" \
          | sort -u \
          | sed 's/.*/local-zone: "&" always_nxdomain/' \
          > "$OUTFILE"

        COUNT=$(wc -l < "$OUTFILE")
        echo "Blocklist updated: $COUNT domains blocked"
        rm -f "$TMPFILE"

        # Reload unbound if it's running
        ${pkgs.unbound}/bin/unbound-control reload 2>/dev/null || true
      '';
      StateDirectory = "unbound";
    };
  };

  systemd.timers.unbound-blocklist = {
    description = "Weekly ad-blocking blocklist update";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      OnBootSec = "5min";   # run 5min after boot (after network is up)
      OnUnitActiveSec = "1w";
      Persistent = true;
    };
  };
  systemd.tmpfiles.rules = [
    "f /var/lib/unbound/blocklist.conf 0644 unbound unbound -"
  ];
}

